import { Link } from "react-router-dom";
function Landing() {
  const coreModules = [
    {
      title: "AI-Powered Plans",
      desc: "Get personalized workout and nutrition plans generated by advanced AI.",
      icon: "🤖",
      accent: "from-purple-500 to-indigo-600",
      id: "MOD-01"
    },
    {
      title: "Real-time Coaching",
      desc: "Adaptive health coach that learns your preferences and adjusts in real-time.",
      icon: "✨",
      accent: "from-blue-500 to-indigo-500",
      id: "MOD-02"
    },
    {
      title: "Goal Tracking",
      desc: "Track your progress with detailed analytics and achievement badges.",
      icon: "📈",
      accent: "from-green-500 to-emerald-600",
      id: "MOD-03"
    },
    {
      title: "Charity Impact",
      desc: "Turn your fitness journey into charitable donations automatically.",
      icon: "❤️",
      accent: "from-red-500 to-rose-600",
      id: "MOD-04"
    },
  ];
  return (
    <div className="min-h-screen bg-[#0a0a0c] text-white selection:bg-white/10 selection:text-white">
      <nav className="fixed top-0 w-full z-50 border-b border-white/5 bg-[#0a0a0c]/80 backdrop-blur-2xl">
        <div className="max-w-screen-2xl mx-auto flex justify-between items-center px-6 md:px-10 py-6">
          <div className="flex items-center gap-10">
            <div className="flex items-center gap-4 group cursor-default">
              <div className="w-10 h-10 bg-white text-black flex items-center justify-center font-black italic text-xl rounded-xl shadow-[0_0_20px_rgba(255,255,255,0.1)]">A</div>
              <div className="flex flex-col">
                <span className="text-xl font-black italic uppercase tracking-tighter leading-none">Arogya<span className="text-white/40">Mitra</span></span>
                <span className="text-[8px] font-black text-white/20 uppercase tracking-[0.4em] leading-none mt-1 text-center">Version 2.0</span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-6">
            <Link to="/login" className="text-[10px] font-black uppercase tracking-[0.3em] text-white/40 hover:text-white transition-colors">Login</Link>
            <div className="h-4 w-[1px] bg-white/10"></div>
            <Link to="/register" className="px-6 py-3 bg-white text-black rounded-xl text-[10px] font-black uppercase tracking-[0.2em] hover:bg-white/90 transition-all">Get Started</Link>
          </div>
        </div>
      </nav>
      <section className="relative min-h-screen flex flex-col items-center justify-center pt-20 overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-7xl aspect-square bg-gradient-to-tr from-white/5 to-transparent blur-[120px] rounded-full pointer-events-none opacity-50"></div>
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-[0.03] pointer-events-none"></div>
        <div className="max-w-7xl mx-auto px-6 md:px-10 text-center space-y-12 relative z-10">
          <div className="space-y-4">
            <h1 className="text-6xl md:text-9xl lg:text-[11rem] font-black tracking-tighter leading-[0.85] uppercase italic">
              Relentless <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-white to-white/20">Evolution</span>
            </h1>
          </div>
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-white/40 leading-relaxed font-medium">
            Engineered with advanced algorithms to architect your physical progress.
            ArogyaMitra is the world's most sophisticated personal health platform.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-6 pt-8">
            <Link to="/register" className="w-full sm:w-auto px-12 py-6 bg-white text-black rounded-[24px] font-black text-sm uppercase italic tracking-[0.2em] hover:bg-white/90 hover:scale-[1.02] active:scale-[0.98] transition-all shadow-2xl shadow-white/5">
              Start Your Journey
            </Link>
          </div>
        </div>
      </section>
      <section className="px-6 md:px-10 py-40 max-w-7xl mx-auto space-y-24">
        <div className="flex flex-col md:flex-row justify-between items-end gap-10">
          <div className="space-y-4 max-w-2xl">
            <h2 className="text-5xl md:text-7xl font-black uppercase italic tracking-tighter leading-none">
              Explore <br />
              <span className="text-white/20">Our Features</span>
            </h2>
            <p className="text-white/40 text-lg font-medium leading-relaxed">
              Every module is designed to interact with your health data in real-time,
              creating a closed-loop system for peak performance.
            </p>
          </div>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {coreModules.map((module, i) => (
            <div key={i} className="bg-[#111114] border border-white/5 p-10 rounded-[40px] space-y-8 group hover:border-white/20 transition-all shadow-xl relative overflow-hidden">
              <div className={`absolute top-0 right-0 p-8 text-5xl opacity-5 group-hover:scale-125 transition-transform duration-700`}>{module.icon}</div>
              <div className="space-y-2 relative z-10">
                <span className="text-[9px] font-black text-white/20 uppercase tracking-[0.3em]">{module.id}</span>
                <h3 className="text-2xl font-black uppercase italic tracking-tighter leading-none group-hover:text-white transition-colors">{module.title}</h3>
              </div>
              <p className="text-sm text-white/40 leading-relaxed font-medium relative z-10 group-hover:text-white/70 transition-colors">
                {module.desc}
              </p>
              <div className="pt-4 relative z-10">
                <div className={`h-1 w-12 bg-gradient-to-r ${module.accent} rounded-full group-hover:w-full transition-all duration-500`}></div>
              </div>
            </div>
          ))}
        </div>
      </section>
      <footer className="px-6 md:px-10 py-20 border-t border-white/5 bg-[#0a0a0c]">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-12 text-center md:text-left">
          <div className="space-y-4">
            <div className="flex items-center justify-center md:justify-start gap-4">
              <div className="w-8 h-8 bg-white text-black flex items-center justify-center font-black italic rounded-lg">A</div>
              <span className="text-lg font-black italic tracking-tighter uppercase">Arogya<span className="text-white/40">Mitra</span></span>
            </div>
          </div>
          <div className="text-right hidden md:block">
            <p className="text-[10px] font-black italic uppercase text-white/40">© 2026 ArogyaMitra Platform</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
export default Landing;