import { Link } from "react-router-dom";
function Landing() {
  const features = [
    {
      title: "AI-Powered Plans",
      desc: "Get personalized workout and nutrition plans generated by advanced AI.",
      icon: "🤖",
      color: "bg-purple-500/20 text-purple-400",
    },
    {
      title: "Real-time Coaching",
      desc: "Adaptive health coach that learns your preferences and adjusts in real-time.",
      icon: "✨",
      color: "bg-blue-500/20 text-blue-400",
    },
    {
      title: "Goal Tracking",
      desc: "Track your progress with detailed analytics and achievement badges.",
      icon: "📈",
      color: "bg-green-500/20 text-green-400",
    },
    {
      title: "Charity Impact",
      desc: "Turn your fitness journey into charitable donations automatically.",
      icon: "❤️",
      color: "bg-red-500/20 text-red-400",
    },
  ];

  return (
    <div className="min-h-screen bg-[#0f111a] text-white">
      <nav className="flex justify-between items-center px-8 py-6 max-w-7xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-purple-600 rounded-lg flex items-center justify-center font-bold">A</div>
          <span className="text-xl font-bold tracking-tight">ArogyaMitra</span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm font-medium text-white/60">
          <a href="#features" className="hover:text-white transition-colors">Features</a>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="text-sm font-medium hover:text-purple-400 transition-colors">Login</Link>
          <Link to="/register" className="btn-primary !px-5 !py-2 text-sm">Get Started</Link>
        </div>
      </nav>
      <section className="relative px-8 pt-20 pb-32 max-w-7xl mx-auto text-center space-y-8 overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 bg-purple-600/10 blur-[120px] -z-10 rounded-full"></div>
        <div className="max-w-4xl mx-auto text-center space-y-8 relative z-10">
          <h1 className="text-6xl md:text-8xl font-black tracking-tighter leading-tight">
            The World's Most <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-600">Intelligent</span> Fitness Companion
          </h1>
          <p className="text-xl text-white/40 max-w-2xl mx-auto leading-relaxed">
            ArogyaMitra isn't just an app—it's a full-stack intelligent system.
            Real-time AI pose tracking, dynamic nutrition planning, and an adaptive health coach that learns and grows with you.
          </p>
          <div className="flex flex-col md:flex-row gap-4 justify-center pt-4">
            <Link to="/register" className="btn-primary !px-10 !py-4 text-lg">Start Your Transformation 🚀</Link>
          </div>
        </div>
      </section>
      
      <section id="features" className="px-8 py-32 max-w-7xl mx-auto space-y-16">
        <div className="text-center space-y-4">
          <h2 className="text-4xl font-bold">Why Choose <span className="text-purple-400">ArogyaMitra?</span></h2>
          <p className="max-w-xl mx-auto text-white/40">Experience the future of fitness with our AI-powered platform that adapts to your lifestyle.</p>
        </div>
        <div className="grid md:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <div key={i} className="glass-card p-8 space-y-6 glass-card-hover group">
              <div className={`w-12 h-12 ${f.color} rounded-xl flex items-center justify-center text-xl group-hover:scale-110 transition-transform`}>
                {f.icon}
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold">{f.title}</h3>
                <p className="text-sm text-white/40 leading-relaxed">{f.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <footer className="px-8 py-12 border-t border-white/5 text-center text-white/20 text-xs font-medium tracking-widest uppercase">
        © 2026 ArogyaMitra. Built for the future of fitness.
      </footer>
    </div>

  );
}
export default Landing;